# Generated by Django 6.0 on 2025-12-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_selling_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
    ]
