# Generated by Django 6.0 on 2026-01-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_selling_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
    ]
