# Generated by Django 6.0 on 2026-01-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_selling_app', '0002_remove_seller_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
